### ISSUE TITLE
Delay on kits dont work if a player has the permission uc.kit.kit.<kitname> + multiple home issue

### ISSUE THREAD

**Issue by EwoutV** [Bammerbom/UltimateCore#16]
Title says it all, I can't seem a way to give a player the permission to set e.g. 3 homes too.

**Comment by JonathanBrouwer** [comment]
For the amount of homes, give the player the permission **OPTION** called uc.home.homecount and set it to 3.
For delay on kits, this will be fixed in the next update

Next time, please create 2 seperate issues.

**Comment by JonathanBrouwer** [comment]
Fixed in https://github.com/Bammerbom/UltimateCore/commit/97cdd133d514940a9c517e52ef9092b26bbf4015

**Comment by EwoutV** [comment]
Alright, thanks, will create two seperate issues in the future... I still don't get it on how that permission works tho..

**Comment by JonathanBrouwer** [comment]
What permissions plugin are you using?
For permissionsex, you can use this command
/pex group Admin option uc.home.homecount 3
For any other plugins, read the documentation or ask their support how to change permission options.

**Comment by EwoutV** [comment]
I'm running luckperms, can't find a way to set that option

**Comment by JonathanBrouwer** [comment]
Take a look at 'meta', which is luckyperms's term for permission options
https://github.com/lucko/LuckPerms/wiki/Chat-Formatting-and-Meta-(Vault)

**Comment by EwoutV** [comment]
Alright, thanks! Sorry for wasting your time :-p

Imo, you should maybe add a home module to manage such things?

**Comment by JonathanBrouwer** [comment]
What do you mean?
In the documentation, you could have found the permission option here:
https://github.com/Bammerbom/UltimateCore/blob/master/docs/modules/home.md

**Comment by EwoutV** [comment]
A module to manage all player's homes, you know what I mean, a bit like how the Essentials plugin handled homes. Also, I don't think I'm the only one who didn't know about permission options, so maybe add a feature in the module where you can choose the amount of homes specific groups can have, instead of giving them the permission option? Those are just ideas, and they might be stupid, since I don't really know anything about Sponge devolepment posibillities atm...

**Comment by JonathanBrouwer** [comment]
Oh you mean commands to manage other player's homes, I understand.
Added to my todo list.

And altough this is possible, I prefer permission options alone because having 2 seperate things to set home amounts might get a mess

**Comment by EwoutV** [comment]
Thanks for adding, and I understand that completely. Also, is it possible for me to get the jar with the fixed cooldowns? Or will there be any new release anytime soon? I need it asap for my updated server :/

**Comment by JonathanBrouwer** [comment]
There should be a new release soon.
But if you want to try the build early, use: https://www.mediafire.com/?2j4ki426o62m2mn
If you use the tablist module, please reset your tablist.conf

**Comment by EwoutV** [comment]
Thank you very much! I do really appreciate it.
